# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [11]:
import numpy as np

2. Create a null vector of size 10 

In [7]:
a = np.zeros(10)

print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3. Create a vector with values ranging from 10 to 49

In [3]:
x = np.arange(10, 49)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


4. Find the shape of previous array in question 3

In [9]:
print(x.shape)

(39,)


5. Print the type of the previous array in question 3

In [10]:
print(x.dtype)

int64


6. Print the numpy version and the configuration


In [24]:
print("Numpy Version: ", np.__version__)
print("\nNumpy Configurations:")
print(np.show_config())

Numpy Version:  1.18.1

Numpy Configurations:
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/aamoo/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/aamoo/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/aamoo/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/aamoo/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/aamoo/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/aamoo/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/aamoo/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/aamoo/anaconda3/include']
None


7. Print the dimension of the array in question 3


In [ ]:
print(x.ndim)

8. Create a boolean array with all the True values

In [29]:
bool_arr = np.ones(10, dtype=bool)
print(bool_arr)

[ True  True  True  True  True  True  True  True  True  True]


9. Create a two dimensional array




In [55]:
arr2d = np.array([[]])
arr2d.ndim

arr2d = np.arange(15).reshape(3, 5)
arr2d.ndim

2

10. Create a three dimensional array



In [57]:
arr3d = np.array([[[]]])
arr3d.ndim

arr3d = np.arange(27).reshape(3, 3, 3)
arr3d.ndim

3

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [4]:
np.flip(x)

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

12. Create a null vector of size 10 but the fifth value which is 1 

In [10]:
z = np.zeros(10)
print("z = ", z)

z[4] = 1
print("Z = ", z)

z =  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Z =  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


13. Create a 3x3 identity matrix

In [14]:
I = np.identity(3)
print("I = \n", I)

I = 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [22]:
arr = np.array([1, 2, 3, 4, 5])
print("arr ", arr)
# arr = np.dtype(float)

arr = arr.astype(np.float64)

print("arr ", arr)

arr  [1 2 3 4 5]
arr  [1. 2. 3. 4. 5.]


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [38]:
# Multiplication of arr1 and arr2 matrix is not possible without transpose because the rows in first martix
# should be equal to the columns in second matrix

arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 

arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])


np.matmul(arr1, arr2.transpose())

array([[ 11.,  47.],
       [ 26., 110.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [40]:
print("Array arr1: \n",arr1)
print("Array arr2: \n",arr2)
print("arr1 > arr2 \n")
print(np.greater(arr1, arr2))
print("arr1 >= arr2 \n")
print(np.greater_equal(arr1, arr2))
print("arr1 < arr2 \n")
print(np.less(arr1, arr2))
print("arr1 <= arr2 \n")
print(np.less_equal(arr1, arr2))

Array arr1: 
 [[1. 2. 3.]
 [4. 5. 6.]]
Array arr2: 
 [[ 0.  4.  1.]
 [ 7.  2. 12.]]
arr1 > arr2 

[[ True False  True]
 [False  True False]]
arr1 >= arr2 

[[ True False  True]
 [False  True False]]
arr1 < arr2 

[[False  True False]
 [ True False  True]]
arr1 <= arr2 

[[False  True False]
 [ True False  True]]


17. Extract all odd numbers from arr with values(0-9)

In [80]:
x = np.arange(0,10)
print(x)

# Method 01
x[x % 2 == 1]

# Method 02
x[1:10:2]

[0 1 2 3 4 5 6 7 8 9]


array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [85]:
# Method 01
x[x % 2 == 1] = -1
print(x)

# Method 02
x[1:10:2] = -1
print(x)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [86]:
# Method 01:
np.put(x, [5, 6, 7, 8], [12])
print(x)

# Method 02:
x[5:9] = 12
print(x)

[ 0 -1  2 -1  4 12 12 12 12 -1]
[ 0 -1  2 -1  4 12 12 12 12 -1]


20. Create a 2d array with 1 on the border and 0 inside

In [60]:
oz = np.ones((5, 5))
print("Orignal Array: \n", oz)

oz[1:-1, 1:-1] = 0
print("\n\nModified Array: \n", oz)

Orignal Array: 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


Modified Array: 
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [64]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])


arr2d[1, 1] = 12

arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [70]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("Orignal: \n", arr3d)

arr3d[0] = 64
print("\n\nModified: \n", arr3d)

Orignal: 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


Modified: 
 [[[64 64 64]
  [64 64 64]]

 [[ 7  8  9]
  [10 11 12]]]


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [98]:
a2d = [[0, 1, 2],
        [3, 4, 5],
       [6, 7, 8]]
print(a2d)

#a2d[1]
print(a2d[1])

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]
[3, 4, 5]


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [106]:
ar = np.arange(9).reshape(3, 3)
print("orignal array:\n", ar)

print("\n\nSecond value from 2nd 1-D array is: ", ar[1, 1])

orignal array:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


Second value from 2nd 1-D array is:  4


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [111]:
ar = np.arange(9).reshape(3, 3)
print("orignal Array:\n", ar)

print("\n\nthe value of first two rows of third column are: \n", ar[0:2, 2])

orignal Array:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


the value of first two rows of third column are: 
 [2 5]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [24]:
myrand = np.array(np.random.randn(10, 10)*10, dtype=np.int)
print("Orignal Array:\n", myrand, "\n\n\n")

minimum = myrand.min()
print("Minimum is: ", minimum)

maximum = myrand.max()
print("\n\nMaximum is: ", maximum)

Orignal Array:
 [[ 13  13   2 -10  11  -2   7   2 -29   0]
 [ 10   1  -2   0   0   2  -9  -7  16  12]
 [  9  10  10  10  -2   7  -9   6   2  -1]
 [  7 -10   8   8  -4 -24   8   2  -8   5]
 [ 27  10  -2  -6 -16   3  -2   5   6  -5]
 [-20  15   1   7   6   7 -15  -1   3  15]
 [  6 -10   1   2   5   7  -7   2  -2 -17]
 [  6 -22   5  -7   0  -3  -3   3 -14  -1]
 [  5 -14   4  -5  -6  10   0   5  11  -7]
 [ -1   0   1  16  -3   2   9  -2  19  10]] 



Minimum is:  -29


Maximum is:  27


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [7]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a, b)

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [9]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a==b)

(array([1, 3, 5, 7]),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [33]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.array(np.random.randn(7, 4) * 10, dtype=np.int)

print("names: \n", names)
print("\n\ndata: \n", data)


names != 'Will'
data[names != 'Will']

names: 
 ['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']


data: 
 [[  3   2  23 -12]
 [ -4  12  -2  -6]
 [ -6   0  -6  -1]
 [ -2   1  -3  10]
 [-10   5  13  -1]
 [ 13   5   8   0]
 [-14   0  13  -4]]


array([[  3,   2,  23, -12],
       [ -4,  12,  -2,  -6],
       [ -2,   1,  -3,  10],
       [ 13,   5,   8,   0],
       [-14,   0,  13,  -4]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [31]:
names == "Will"

data[names == 'Will']

array([[ -7,   4,  22,   2],
       [  2,  -5,   0, -19]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [38]:
arr2d = np.arange(1, 16).reshape(5, 3)
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [46]:
# 2 x 2 x 3 = 12. We can not use 16 numbers to create this 3D array

arr3d = np.arange(1, 13).reshape(2, 2, 3)
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

33. Swap axes of the array you created in Question 32

In [51]:
swapxy = np.swapaxes(arr3d, 0, 1)

swapxz = np.swapaxes(arr3d, 0, 2)

swapyz = np.swapaxes(arr3d, 1, 2)

print("SwapXY:\n", swapxy)
print("\nSwapXZ:\n", swapxz)
print("\nswapYZ:\n", swapyz)

SwapXY:
 [[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]

SwapXZ:
 [[[ 1  7]
  [ 4 10]]

 [[ 2  8]
  [ 5 11]]

 [[ 3  9]
  [ 6 12]]]

swapYZ:
 [[[ 1  4]
  [ 2  5]
  [ 3  6]]

 [[ 7 10]
  [ 8 11]
  [ 9 12]]]


34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [93]:
s = np.random.randn(10)
s[s < 0] = 1
srt = np.sqrt(s)



print("Array:\n", s)
print("\nSquare Root of every element:\n", srt)

srt[srt < 0.5] = 0
print("\nAll values less than 0.5 is 0:\n", srt)

Array:
 [0.52205002 1.7703749  1.         1.         0.07739088 0.3587519
 0.205001   1.95099657 0.24492781 1.        ]

Square Root of every element:
 [0.72253029 1.33055436 1.         1.         0.27819217 0.59895901
 0.45277037 1.39678079 0.49490182 1.        ]

All values less than 0.5 is 0:
 [0.72253029 1.33055436 1.         1.         0.         0.59895901
 0.         1.39678079 0.         1.        ]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [100]:
x = np.array(np.random.random(12)* 10, dtype=np.int)
y = np.array(np.random.random(12)* 10, dtype=np.int)

print("X: \n", x)
print("Y: \n", y)

z = np.maximum(x, y)
print("Z:\n", z)

X: 
 [7 2 4 7 9 7 1 7 1 3 9 0]
Y: 
 [7 5 5 4 1 4 5 5 6 6 7 3]
Z:
 [7 5 5 7 9 7 5 7 6 6 9 3]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [105]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
unames = np.unique(names)

print("Names:\n", names)
print("Unique Names:\n", unames)

Names:
 ['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
Unique Names:
 ['Bob' 'Joe' 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [107]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])

a[b[np.searchsorted(b,a)] !=  a]

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [119]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])

#sampleArray
#newColumn

sampleArray[:,2] = newColumn
sampleArray

array([[34, 43, 10],
       [82, 22, 10],
       [53, 94, 10]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [120]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])

np.matmul(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [124]:
mat = np.array(np.random.random(20)*10, dtype=np.int)
csum = np.cumsum(mat)

print("Orignal Array:\n", mat)
print("\n\nComulative Sum:\n", csum)

Orignal Array:
 [0 4 7 2 4 2 0 9 9 7 6 5 6 6 6 7 5 8 8 8]


Comulative Sum:
 [  0   4  11  13  17  19  19  28  37  44  50  55  61  67  73  80  85  93
 101 109]
