# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [5]:
import numpy as np

x = np.arange(10)
print("x:\n", x)
print("\n\n=============\n\n")

x = x.reshape(2, 5)
print("x:\n", x)

x:
 [0 1 2 3 4 5 6 7 8 9]




x:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [40]:
#import numpy as np
x = np.arange(10).reshape(2,5)
y = np.ones((2, 5))
print("x:\n", x, "\n\n=========================\n\ny:\n", y)

np.vstack((x, y)).astype(int)

x:
 [[0 1 2 3 4]
 [5 6 7 8 9]] 


y:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [47]:
#x = np.array([0, 1, 2, 3, 4, 1, 1, 1, 1, 1])
#y = np.array([5, 6, 7, 8, 9, 1, 1, 1, 1, 1])
x = np.arange(10).reshape(2,5)
x

y = np.ones((2, 5))
y
np.hstack((x, y))

array([[0., 1., 2., 3., 4., 1., 1., 1., 1., 1.],
       [5., 6., 7., 8., 9., 1., 1., 1., 1., 1.]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [54]:
x = np.arange(1, 10).reshape(3, 3)
y = x.flatten()

print("x:\n", x, "\n\n=========================\n\ny:\n", y)

x:
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 


y:
 [1 2 3 4 5 6 7 8 9]


## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [61]:
x = np.arange(15).reshape(3, 5)
print("x:\n", x, "\n\n=========================\n\nOne Diamension:")
x.ravel()

x:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 


One Diamension:


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [66]:
x = np.arange(15)
y = x.reshape(5, 3)

print("x:\n", x, "\n\n=========================\n\ny:\n", y)

x:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14] 


y:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


## Question:7

### Create 5x5 an array and find the square of an array?

In [71]:
x = np.arange(25).reshape(5, 5)
y = np.square(x)

print("x:\n", x, "\n\n=========================\n\nSquare of x:\n", y)

x:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 


Square of x:
 [[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]
 [225 256 289 324 361]
 [400 441 484 529 576]]


## Question:8

### Create 5x6 an array and find the mean?

In [75]:
x = np.arange(30).reshape(5, 6)
y = np.mean(x)

print("x:\n", x, "\n\n=========================\n\nMean of x:\n", y)

x:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]] 


Mean of x:
 14.5


## Question:9

### Find the standard deviation of the previous array in Q8?

In [77]:
y = np.std(x)

print("x:\n", x, "\n\n=========================\n\nStandard Deviation of x:\n", y)

x:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]] 


Standard Deviation of x:
 8.65544144839919


## Question:10

### Find the median of the previous array in Q8?

In [78]:
y = np.median(x)

print("x:\n", x, "\n\n=========================\n\nMedian of x:\n", y)

x:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]] 


Median of x:
 14.5


## Question:11

### Find the transpose of the previous array in Q8?

In [79]:
y = x.T

print("x:\n", x, "\n\n=========================\n\nTranspose of x:\n", y)

x:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]] 


Transpose of x:
 [[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]


## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [86]:
x = np.arange(1, 17).reshape(4, 4)
y = np.trace(x)

print("x:\n", x, "\n\n=========================\n\nSum of Diagonal elements of x:\n", y)

x:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 


Sum of Diagonal elements of x:
 34


## Question:13

### Find the determinant of the previous array in Q12?

In [87]:
y = np.linalg.det(x)
y

4.7331654313261276e-30

## Question:14

### Find the 5th and 95th percentile of an array?

In [91]:
x = np.arange(1, 17).reshape(4, 4)
y5 = np.percentile(X, 5)
y95 = np.percentile(X, 95)

print("x:\n", x, "\n\n=========================\n\n5th Percentile of x:\n", y5, "\n\n=========================\n\n95th Percentile of x:\n", y95)

x:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 


5th Percentile of x:
 1.75 


95th Percentile of x:
 15.25


## Question:15

### How to find if a given array has any null values?

In [97]:
x = np.arange(1, 17).reshape(4, 4)
y = np.isnan(x).any()
y

False